name: Manual examples deployment

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'CD | TAG | MANUAL'
        required: false
        default: MANUAL

  pull_request:


jobs:
  python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare environment
        run: |
          sudo apt update && sudo apt install ffmpeg
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install --no-cache-dir ".[full,test]"
      - name: Add JCloud auth token
        run: |
          mkdir -p ~/.jina
          touch ~/.jina/config.json
          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
          cat ~/.jina/config.json
        env:
          WOLF_TOKEN: ${{ secrets.WOLF_EXAMPLES_TOKEN }}
      - name: Deploy examples
        run: python now/admin/deploy_examples.py
        env:
          WOLF_TOKEN: ${{ secrets.WOLF_EXAMPLES_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
