name: (temporary worfklow) Dump now Secrets

on:
  workflow_dispatch:
    inputs:
      release:
        description: Pass the jina-now release
        required: true
        default: latest
  pull_request:

jobs:
  now-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Read secrets from repo into environment variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          HUBBLE_AUTH_TOKEN: ${{ secrets.HUBBLE_AUTH_TOKEN }}
          JINA_DEV_BOT: ${{ secrets.JINA_DEV_BOT }}
          JINA_OPTOUT_TELEMETRY: ${{ secrets.JINA_OPTOUT_TELEMETRY }}
          NETLIFY_AUTH_TOKEN1: ${{ secrets.NETLIFY_AUTH_TOKEN1 }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NOW_ANNLITE_EXECUTOR_SECRET: ${{ secrets.NOW_ANNLITE_EXECUTOR_SECRET }}
          NOW_AUTH_EXECUTOR_SECRET: ${{ secrets.NOW_AUTH_EXECUTOR_SECRET }}
          NOW_AUTOCOMPLETE_SECRET: ${{ secrets.NOW_AUTOCOMPLETE_SECRET }}
          NOW_ELASTIC_EXECUTOR_SECRET: ${{ secrets.NOW_ELASTIC_EXECUTOR_SECRET }}
          NOW_OCR_EXECUTOR_SECRET: ${{ secrets.NOW_OCR_EXECUTOR_SECRET }}
          NOW_POSTPROCESSOR_EXECUTOR_SECRET: ${{ secrets.NOW_POSTPROCESSOR_EXECUTOR_SECRET }}
          NOW_PREPROCESSOR_JCLOUD_TOKEN: ${{ secrets.NOW_PREPROCESSOR_JCLOUD_TOKEN }}
          NOW_PREPROCESSOR_REPO: ${{ secrets.NOW_PREPROCESSOR_REPO }}
          NOW_PREPROCESSOR_REPO_TOKEN: ${{ secrets.NOW_PREPROCESSOR_REPO_TOKEN }}
          NOW_QDRANT_EXECUTOR_SECRET: ${{ secrets.NOW_QDRANT_EXECUTOR_SECRET }}
          NOW_STAGING_FLORIAN: ${{ secrets.NOW_STAGING_FLORIAN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          WOLF_EXAMPLES_TOKEN: ${{ secrets.WOLF_EXAMPLES_TOKEN }}
          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
        run: |
          echo $AWS_ACCESS_KEY_ID >> secrets.txt
          echo $AWS_HOSTED_ZONE_ID >> secrets.txt
          echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
          echo $DOCKER_PASSWORD >> secrets.txt
          echo $DOCKER_USERNAME >> secrets.txt
          echo $HUBBLE_AUTH_TOKEN >> secrets.txt
          echo $JINA_DEV_BOT >> secrets.txt
          echo $JINA_OPTOUT_TELEMETRY >> secrets.txt
          echo $NETLIFY_AUTH_TOKEN1 >> secrets.txt
          echo $NETLIFY_SITE_ID >> secrets.txt
          echo $NOW_ANNLITE_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_AUTH_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_AUTOCOMPLETE_SECRET >> secrets.txt
          echo $NOW_ELASTIC_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_OCR_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_POSTPROCESSOR_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_PREPROCESSOR_JCLOUD_TOKEN >> secrets.txt
          echo $NOW_PREPROCESSOR_REPO >> secrets.txt
          echo $NOW_PREPROCESSOR_REPO_TOKEN >> secrets.txt
          echo $NOW_QDRANT_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_STAGING_FLORIAN >> secrets.txt
          echo $PERSONAL_ACCESS_TOKEN >> secrets.txt
          echo $S3_IMAGE_TEST_DATA_PATH >> secrets.txt
          echo $TWINE_PASSWORD >> secrets.txt
          echo $TWINE_USERNAME >> secrets.txt
          echo $WOLF_EXAMPLES_TOKEN >> secrets.txt
          echo $WOLF_TOKEN >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
