name: Update Durations
on:
#  workflow_dispatch:
  pull_request:

jobs:
  update-durations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Add JCloud auth token
        run: |
          mkdir -p ~/.jina
          touch ~/.jina/config.json
          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
          cat ~/.jina/config.json
        env:
          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
      - name: create durations
        id: test
        run: |
          pytest --suppress-no-test-exit-code -v -s -m "not gpu" --store-durations tests/
        timeout-minutes: 100
        env:
          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
          S3_SCHEMA_FOLDER_PATH: ${{ secrets.S3_SCHEMA_FOLDER_PATH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_CUSTOM_DATA_PATH: ${{ secrets.S3_CUSTOM_DATA_PATH }}

#      - name: Commit and push new durations file
#        run: |
#        git config user.email "github-actions@github.com"
#        git config user.name "Github Actions"
#        git add durations.json
#        git commit -m "Update test durations"
#        git push origin HEAD
#        env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Create pull request
#        uses: peter-evans/create-pull-request@v2
#        with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        commit-message: "Update test durations"
#        title: "Update test durations"
#        head: "update-durations"
#        base: "main"
#        labels: "duration, tests"
#        env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}